Metrics/LineLength:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/AlignHash:
  Severity: fatal
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Layout/DotPosition:
  EnforcedStyle: leading

Style/DoubleNegation:
  Enabled: false

Layout/SpaceAroundOperators:
  # When true, allows most uses of extra spacing if the intent is to align
  # with an operator on the previous or next line, not counting empty lines
  # or comment lines.
  AllowForAlignment: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DateTime:
  Enabled: false

AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
